import type { CollectionConfig } from 'payload'

export const UploadSessions: CollectionConfig = {
  slug: 'upload-sessions',
  access: {
    admin: () => false,
    create: () => false,
    delete: () => false,
    read: () => false,
    update: () => false,
  },
  admin: { hidden: true, useAsTitle: 'uploadSessionId' },
  lockDocuments: false,
  fields: [
    { name: 'uploadSessionId', type: 'text', required: true, unique: true, index: true },
    { name: 'organisation', type: 'relationship', relationTo: 'organisations', index: true },
    { name: 'folder', type: 'relationship', relationTo: 'media-folders', index: true },
    {
      name: 'mediaProtectionPolicy',
      type: 'select',
      options: ['protected', 'standard'],
      defaultValue: 'protected',
    },
    { name: 'retentionDays', type: 'number' },
    {
      name: 'asset',
      type: 'relationship',
      relationTo: 'media-assets',
      required: true,
      unique: true,
    },
    {
      name: 'owner',
      type: 'relationship',
      relationTo: 'members',
      required: true,
      index: true,
    },
    { name: 'fileName', type: 'text', required: true },
    { name: 'mimeType', type: 'text', required: true },
    { name: 'size', type: 'number', required: true },
    { name: 'fileFingerprint', type: 'text', required: true },
    { name: 'providerUploadId', type: 'text', required: true, unique: true, index: true },
    { name: 'providerUploadData', type: 'text' },
    { name: 'partSize', type: 'number', required: true },
    { name: 'objectKey', type: 'text' },
    {
      name: 'status',
      type: 'select',
      options: ['pending', 'completed', 'aborted', 'expired'],
      required: true,
    },
    { name: 'expiresAt', type: 'date', required: true },
  ],
  timestamps: true,
}
