import type { CollectionConfig } from 'payload'

export const ProcessingJobs: CollectionConfig = {
  slug: 'processing-jobs',
  access: {
    admin: () => false,
    create: () => false,
    delete: () => false,
    read: () => false,
    update: () => false,
  },
  admin: { hidden: true, useAsTitle: 'processingJobId' },
  fields: [
    { name: 'processingJobId', type: 'text', required: true, unique: true, index: true },
    { name: 'organisation', type: 'relationship', relationTo: 'organisations', index: true },
    { name: 'providerJobId', type: 'text', unique: true, index: true },
    {
      name: 'asset',
      type: 'relationship',
      relationTo: 'media-assets',
      required: true,
      unique: true,
    },
    {
      name: 'owner',
      type: 'relationship',
      relationTo: 'members',
      required: true,
      index: true,
    },
    {
      name: 'status',
      type: 'select',
      options: ['queued', 'dispatching', 'processing', 'ready', 'failed'],
      required: true,
    },
    { name: 'queuedAt', type: 'date', required: true },
    { name: 'dispatchBy', type: 'date', required: true, index: true },
    { name: 'nextAttemptAt', type: 'date', required: true, index: true },
    { name: 'attempts', type: 'number', required: true, defaultValue: 0 },
    { name: 'leaseToken', type: 'text', index: true },
    { name: 'leasedUntil', type: 'date', index: true },
    { name: 'dispatchedAt', type: 'date' },
    { name: 'startedAt', type: 'date' },
    { name: 'processingDeadlineAt', type: 'date', index: true },
    { name: 'readyAt', type: 'date' },
    { name: 'failedAt', type: 'date' },
    { name: 'failureCode', type: 'text' },
    { name: 'failureMessage', type: 'text' },
    { name: 'objectKey', type: 'text', required: true },
    { name: 'sourceWidth', type: 'number', required: true },
    { name: 'sourceHeight', type: 'number', required: true },
    { name: 'sourceDurationSeconds', type: 'number', required: true },
    { name: 'renditions', type: 'json', required: true },
  ],
  timestamps: true,
}
